### ISSUE TITLE
Audio level changes do not reflect for MSM8994 devices

### ISSUE THREAD

**Issue by gus33000** [gus33000/MSM8994-8992-NT-ARM64-Drivers#27]

**Comment by gus33000** [comment]
Some misconfiguration has been found regarding subsys as well as a bug with the inf itself, see #f8e90459f156e0d389403297bb4470e8bfb7884a and #e1d829c6bd444e85d03ce827b9c4b8fba9278fb2

**Comment by DjArt** [comment]
Talkman handset speaker don't reflect too.

**Comment by gus33000** [comment]
> Talkman handset speaker don't reflect too.

That's intended

**Comment by gus33000** [comment]
Fixed by 232bc59
