### ISSUE TITLE
Set up a CI

### ISSUE THREAD

**Issue by cleveHEX** [gus33000/MSM8994-8992-NT-ARM64-Drivers#4]
So f98ff695e438a752a98e49f529b710d15d3f7dee won't happen again - @superjmn will have better sleeping.

**Comment by edude03** [comment]
I'd like to help with this if I can - I assume we need the CI machine connected to physical phones however?

**Comment by gus33000** [comment]
Yeah that's the hardest part. I do have test phones for that but I need to gather UART cables for them.

**Comment by gus33000** [comment]
For now we're doing tests in a separate branch but we still would need automated testing some day.

**Comment by gus33000** [comment]
Closing as we already have a test hardness setup
