### ISSUE TITLE
Loading the internal accumulator

### ISSUE THREAD

**Issue by pachnes** [gus33000/MSM8994-8992-NT-ARM64-Drivers#50]
Hi,

I would like a mode to charge the accumulator, when the phone is off (battery drain is very fast and qi loading is slower than drain :) ). Can you implement a menu point in bootmgr, where the phone does  charge the accumulator and the phone does not start to boot, before I allow it.

**Comment by quiret** [comment]
Good idea. It is cumbersome that the phone keeps starting even though I just want it to charge.

**Comment by gus33000** [comment]
Closing the issue as it's unrelated to this driver repository and related to the hardware itself
