### ISSUE TITLE
WOA Diaier can‘t open in 1909v2,1910 and 1910-release!!! 

### ISSUE THREAD

**Issue by bihaiqiongtian** [gus33000/MSM8994-8992-NT-ARM64-Drivers#53]
Please attention and repair it~~thanks~~~
                                                                 --------from  Chinese fans

**Comment by bihaiqiongtian** [comment]
I have tried it in the release of 18875pro and 18908home-China

**Comment by bihaiqiongtian** [comment]
When WOA Diaier can't open ,incoming telegram any voice.

**Comment by gus33000** [comment]
Issues about woadialer must be posted here: https://github.com/WOA-Project/woadialer/issues

this issue is marked as invalid
