### ISSUE TITLE
Windows Update is broken with patched mobile settings dll

### ISSUE THREAD

**Issue by pachnes** [gus33000/MSM8994-8992-NT-ARM64-Drivers#54]
Hi Gus!

Lumia 950XL, single SIM:

There is some issue with 1910-release. Deployment does not work with Windows 10 Pro 18363.388. But deployment does work with Windows 10 Pro 18362.356. After deployment of Windows 10 Pro 18362.356 windows update does find update to Windows 10 Pro 18362.388, it does try to install it, but it can not, it does never finish.

1909-release does take deployment of both initial Windows 10 Pro 18362.356 and initial Windows 10 Pro 18363.388. When I deploy Windows 10 Pro 18362.356, windows update does find an update to Windows 10 Pro 18362.388 and this does install well. After a reboot windows update does find Windows 10 Pro 18363.388 and does install it well.

So there is something wrong with 1910-release :(

Regards and thank you very much!
Thomas

**Comment by gus33000** [comment]
This is not an easy thing to fix, either we have network mobile settings working or no WU working. i tested new deployments they work fine here, there's an issue with your setup. I'm not going to close this but if no dev picks that issue up then it won't get fixed

I'm not working on this project anymore so it's not really up to me anymore
