### ISSUE TITLE
Attempting to Use Cellular, "Account Not Active"

### ISSUE THREAD

**Issue by DremOSDeveloperTeam** [gus33000/MSM8994-8992-NT-ARM64-Drivers#55]
I've seen some videos on YouTube where cellular is working, but my device still says "Account Not Active." Are the drivers being worked on but just haven't been pushed to the repository, or am I missing something? I'm using T-Mobile if that helps.

I know this issue is quite similar to [this one](https://github.com/WOA-Project/MSM8994-8992-NT-ARM64-Drivers/issues/11), but I see the IMEI number and other things in the settings for cellular, so I thought that I may have the drivers for cellular but there may be an issue with T-Mobile. Thanks!

**Comment by gus33000** [comment]
Your issue is the same issue as #24 Closing as this is a duplicate. If you want cellular to work use build 18363 max.

**Comment by DremOSDeveloperTeam** [comment]
oh, thanks, didnt see that 18363 is the maximum build that works with cellular in that issue so i decided to make another issue since it was closed.
