### ISSUE TITLE
Usb Mouse

### ISSUE THREAD

**Issue by szy251** [gus33000/MSM8994-8992-NT-ARM64-Drivers#57]
Im trying conect my mouse to the phone, but hub doesnt work. There is no output voltage,but i can charge my phone. I try instal some drivers and change in registry values but it doesnt help.

**Comment by SuperJMN** [comment]
Try the built-in application called "USB function mode switcher" and enable current, BUT BE CAREFUL. You absolutely must not plug your Lumia to anything that provides current while in this mode.

Alternatively, you can set the default "unpowered" host mode with a powered dock.

**Comment by szy251** [comment]
Where built it? And im not suere abot output voltage.

**Comment by szy251** [comment]
Nevewr mind I find it
