### ISSUE TITLE
Lumia 950 turn into blue screen first boot after deploy:driver pnp watchdog

### ISSUE THREAD

**Issue by CxZMoE** [gus33000/MSM8994-8992-NT-ARM64-Drivers#68]
Installed Image:19551.1005.200119-2325.RS_PRERELEASE_FLT_CLIENTPRO_OEMRET_A64FRE_ZH-CN.ISO
Machine Type: Lumia 950XL
Stop Code: driver pnp watchdog

**Comment by CxZMoE** [comment]
I chose this from uups:Windows 10 Insider Preview 10.0.19551.1005 (rs_prerelease) arm64

**Comment by CxZMoE** [comment]
and now I'm trying 19456

**Comment by CxZMoE** [comment]
and it still the same thing. now try 18950

**Comment by SuperJMN** [comment]
Don't try anything newer than 19041.
________________________________

**Comment by SuperJMN** [comment]
Important note: Manganese builds are unsupported, the maximum build you can install and use is build 19041

**Comment by SuperJMN** [comment]
Not related to WOA Deployer

**Comment by CxZMoE** [comment]
thanks a lot!!!
