### ISSUE TITLE
WLAN on Lumia 950 (not XL)

### ISSUE THREAD

**Issue by TSlivede** [gus33000/MSM8994-8992-NT-ARM64-Drivers#9]
"[Lumia 950 mit Windows 10 ARM unterstüzt jetzt WLAN-Treiber](https://windowsarea.de/2019/03/lumia-950-mit-windows-10-arm-unterstuezt-jetzt-wlan-treiber/)" says, that WLAN is working on the Lumia 950. However this project's [README.md](https://github.com/WOA-Project/MSM8994-8992-NT-ARM64-Drivers/blob/main/README.md) still lists WLAN as not working.

So my question is: Should WLAN work on the Lumia 950?

**Comment by gus33000** [comment]
WLAN doesn't work on Lumia 950s. That's also an UEFI issue, not an issue with drivers.
